# Based on https://raw.githubusercontent.com/commercialhaskell/stack/master/doc/travis-simple.yml

language: generic

sudo: false

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
      # For GHC
      - libgmp-dev
      
before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- travis_wait stack --no-terminal --install-ghc test --only-dependencies
- stack --no-terminal test --coverage
- stack --no-terminal install hfmt
- stack --no-terminal exec hfmt


after_script:
- travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar -xj
- ./shc ProC spec
      