
print("The number is:        2=" ++ tos(2));
print("Negated:             -2=" ++ tos(-2));
print("Multiply:           2*2=" ++ tos(2 * 2));
print("Order of ops:   2*3 + 2=" ++ tos(2*3 + 2));
print("Brackets:     2 * (3+2)=" ++ tos(2*(3+2)));

int a = 42;
int b = 13;

print("Variables:            a=" ++ tos(a));
print("Variables:          2*a=" ++ tos(2*a));
print("Two Variables:      a+b=" ++ tos(a+b));


